title: Cowork Toolkit
description: Community-built Microsoft 365 Copilot Cowork Prompts and More
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

github_pat: "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"
